begin;
drop function if exists public.integritas_pause_case_investigation(uuid,uuid);
drop function if exists public.integritas_resume_case_investigation(uuid,uuid);
drop function if exists public.integritas_acknowledge_case_investigation_pause(uuid,text,uuid);
drop function if exists public.integritas_finalize_document_delete(uuid,uuid,uuid);
drop function if exists integritas_private.integritas_pause_case_investigation(uuid,uuid);
drop function if exists integritas_private.integritas_acknowledge_case_investigation_pause(uuid,text,uuid);
drop function if exists integritas_private.integritas_resume_case_investigation(uuid,uuid);
drop function if exists integritas_private.integritas_finalize_document_delete(uuid,uuid,uuid);
alter table public.integritas_case_jobs drop column if exists pause_requested;
alter table public.integritas_control_commands drop constraint if exists integritas_control_commands_status_check;
alter table public.integritas_control_commands add constraint integritas_control_commands_status_check check (status in ('queued','leased','running','completed','failed','cancelled'));
commit;
